### ISSUE TITLE
Include Hour/Minute timestamps

### ISSUE THREAD

**Issue by katuwiran** [BilliAlpha/discord-transfer#5]
First of all, thank you for the bot!

This is a small feature request. For the sake of archiving a server of ours, I'd also like to see the HH:MM timestamp as well aside from the date.

**Comment by BilliAlpha** [comment]
Hello,

In order to show the date of the message I am using a specific `timestamp` field for embeds.

The way this field is shown in the discord app does not seem to be configurable.

It seems that discord chose to not show the time when the message is too old.

The API method used is: https://www.javadoc.io/static/com.discord4j/discord4j-core/3.1.3/discord4j/core/spec/EmbedCreateSpec.html#setTimestamp-java.time.Instant-

If you still want to show the time with a custom format you could try to add a specific field.

If I were to implement it, I would pass it as an opt-in command line option, unfortunately I won't have the time to take a crack at it any time soon. If you would like to make a PR for it I'd be glad to help you however.

**Comment by BilliAlpha** [comment]
It seems discord has updated the display of the embeds date:
![image](https://user-images.githubusercontent.com/17186697/204576944-50381d0c-ccef-4d9a-a0bb-7b02156799f1.png)
